### ISSUE TITLE
Getting started impl manifest does not work

### ISSUE THREAD

**Issue by inf17101** [Green-Software-Foundation/if-docs#27]
## Scope

What does your feedback relate to?

- [] Project aims/objectives
- [] Repository structure 
- [x] Model plugin
- [] Rimpl code 
- [x] Documentation
- [] Tests
- [] Other

## Details

The Getting Started example manifest (impl) does not work. The impact-engine outputs with `Invalid Input`.

Error msg:
```
InputValidationError: Invalid input
    at validate (/usr/lib/node_modules/@grnsft/if-models/build/util/validations.js:38:15)
    at SciModel.validateInput (/usr/lib/node_modules/@grnsft/if-models/build/lib/sci/index.js:99:43)
    at /usr/lib/node_modules/@grnsft/if-models/build/lib/sci/index.js:26:36
    at Array.map (<anonymous>)
    at SciModel.execute (/usr/lib/node_modules/@grnsft/if-models/build/lib/sci/index.js:25:36)
    at Observatory.doInvestigationsWith (/usr/lib/node_modules/@grnsft/if/build/lib/observatory.js:20:44)
    at Supercomputer.calculateOutputsForChild (/usr/lib/node_modules/@grnsft/if/build/lib/supercomputer.js:103:31)
    at async Supercomputer.compute (/usr/lib/node_modules/@grnsft/if/build/lib/supercomputer.js:139:13)
    at async impactEngine (/usr/lib/node_modules/@grnsft/if/build/index.js:38:22)
```

If I extend the validation file output in the error traceback above (/usr/lib/node_modules/@grnsft/if-models/build/util/validations.js:37:15) and add a `console.log(validationResult.error);` at line 37, then there is more information about the error available:

```
ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "functional-unit-time"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "number",
            "received": "undefined",
            "path": [
              "carbon"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "string",
            "received": "undefined",
            "path": [
              "functional-unit-time"
            ],
            "message": "Required"
          },
          {
            "code": "invalid_type",
            "expected": "number",
            "received": "undefined",
            "path": [
              "embodied-carbon"
            ],
            "message": "Required"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [],
    "message": "Invalid input"
  }
]
```

If I add the new fields mentioned inside the error context above, I still get the error.

Hopefully, this helps.

## Expected Behaviour

Examples shall work.

## Actual behaviour

When using the example impl https://github.com/Green-Software-Foundation/if-docs/blob/master/docs/04-getting-started.md#3-create-a-manifest-file, the impact engine outputs an error that the input config is invalid.

## Proposed actions

What fixes do you propose?
Fix the example or the model input.

**Note: We will take all feedback seriously. Please be polite and constructive - aggressive or abusive feedback will simply be deleted.**

**Comment by jmcook1186** [comment]
Hello, thanks for catching this - we refactored the models recently and this example slipped through the net - we're fixing it now.

**Comment by jmcook1186** [comment]
Closing as fixed
