### ISSUE TITLE
Marketing Plan

### ISSUE THREAD

**Issue by jawache** [Green-Software-Foundation/if-docs#7]
- [ ] Communicate with commitee
- [ ] #8
- [ ] Paid promotion on dev.to
- [ ] Contact meetup organiziers to promote
- [ ] Social media campaign
- [ ] Webinar1
- [ ] Think about this....

**Comment by jmcook1186** [comment]
Linking with "global" milestone tracker in IF repo https://github.com/Green-Software-Foundation/if/issues/311

**Comment by jawache** [comment]
Sorry will close this, was just for demo purposes
